### ISSUE TITLE
About working memory dataset

### ISSUE THREAD

**Issue by Qiliu-maker** [Anwar-Said/NeuroGraph#10]
Hello，I have already read the document, and there are Brain_Connectome_Rest_Download and Brain_Connectome_State_Download. I want to know how to obtain the working memory dataset, or if I already have the working memory dataset listed in Table 8 of the appendix, how should I process it?
look forward to your reply

**Comment by Anwar-Said** [comment]
Thanks for reaching out!

If you’ve already downloaded the data, the instances with class 6 correspond to working memory. You might also consider downloading the refined datasets.

**Comment by Qiliu-maker** [comment]
I am a bit unclear: in your code, the working memory dataset is derived from the rest dataset and the task dataset. Is it correct for me to use that 527GB raw working memory dataset?And I would like to first replicate the results in your paper.
Thank you for your response!

**Comment by Anwar-Said** [comment]
I think so, but the refined WM dataset is already available on PyG. Please take a look at that. 

https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.datasets.NeuroGraphDataset.html#torch_geometric.datasets.NeuroGraphDataset
