### ISSUE TITLE
About other tasks

### ISSUE THREAD

**Issue by good-demo** [Anwar-Said/NeuroGraph#4]
Thank you for your work. Currently, only the code for classification tasks is provided. Would you consider opening up the code for other tasks?

**Comment by Anwar-Said** [comment]
Thank you for reaching out and taking interest in NeuroGraph. For the regression task, you just need to change the number of neurons from num_classes to 1 in the GNN class (forward func) and use a different (regression) loss.

**Comment by good-demo** [comment]
Thanks for your quick response.
