### ISSUE TITLE
Model related to NeuroGraphDynamic dataset

### ISSUE THREAD

**Issue by rovenallapushi** [Anwar-Said/NeuroGraph#5]
Hello :) I have read the published paper carefully and noticed architecture for learning dynamic graph representations. I was wondering if would be possible to  access information on how the model is used when having as input NuroGraphDynamic dataset. 

Thanks!

**Comment by Anwar-Said** [comment]
Hi, 
Thanks for taking a look at the work.
Please see the documentation here: https://neurograph.readthedocs.io/en/latest/datasets.html

The dynamic graphs related to one subject are in one pyg batch and can be easily broadcasted to any pipeline. We have not yet publicly released the implementation for the dynamic pipeline, as the work is quite preliminary. However, I will upload it soon.

**Comment by rovenallapushi** [comment]
Hi, thanks for your quick reply and support.
