### ISSUE TITLE
Table #3 revised on arXiv

### ISSUE THREAD

**Issue by Supgb** [Anwar-Said/NeuroGraph#6]
The **Gender classification** part of *Table 3* contains two duplicate rows of results:
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/a3406613-c587-46cb-bf00-9140df4e71d9">

The results for *medium*-level sparsity are identical between *100ROIs* and *400ROIs*, which contradict those presented in *Table 2*.

**Comment by Anwar-Said** [comment]
Thanks for raising the issue. Greatly appreciated.  arXiv version has been revised accordingly.
