### ISSUE TITLE
About dynamic and static graphs dataset

### ISSUE THREAD

**Issue by izeyasd** [Anwar-Said/NeuroGraph#9]
Hello! I'm a little confused why there are two more graphs in a dynamic graph than in a static graph, and whether the dynamic graph and the static graph are obtained from the same people, and how do I match them,look forward to your response
Thank you!

**Comment by Anwar-Said** [comment]
Hi, 
Datasets for different tasked were preprocessed separately. Likewise, the preprocessing between the static and dynamic graphs are different, which differs the number of samples. Moreover, there was no mapping maintained between the subjects in different task datasets. But I think it would be possible to maintain the mapping. Please check the NeuroGraph documentation. You may need to process the data again to get the mapping.

**Comment by izeyasd** [comment]
I am a little confused that different processing methods will have different graphs, is not a person corresponding to a graph
Thank you for your reply

**Comment by Anwar-Said** [comment]
Please see the detail on preprocessing in section 3.2 and section C in Appendix which describe how the data was processed in static and dynamic setting. Mainly, in the static setting, two subjects that contained fewer than 1200 scans were removed to keep the preprocessing align for every sample.
